name: upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to Dropbox
        uses: Lewuathe/dropbox-github-action@v1
        with:
          dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
          dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: ./cv/aliaksandr-valchetski-cv.pdf
          target-path: /cv/aliaksandr-valchetski-cv.pdf
