name: upload

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dropbox Upload 📦
        uses: gomes42/gh-actions-dropbox/files/upload@v0.0.1
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          SOURCE_PATH: ./cv/aliaksandr-valchetski-cv.pdf
          DEST_PATH: /aliaksandr-valchetski-cv.pdf
