name: upload

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: ./cv/aliaksandr-valchetski-cv.pdf
          dest: /cv/
          mode: overwrite
